### ISSUE TITLE
Freeplane version should be written as a string

### ISSUE THREAD

**Issue by EdoFro** [barrymac/freeplane_openai_addon#1]
Hi @barrymac,
In your add-on map, you wrote the Freeplane version as a number: `1.9` . 
In my case Freeplane changed the dot for a comma because decimal numbers are written that way around here. 
And it throws the following error message:

```
WARNING: installation failure
java.lang.Exception: Error in map structure: Format error in freeplaneVersionFrom (value: 1.9)
```

### can you please write the Freeplane version this way: `v1.9`?

like:
![image](https://user-images.githubusercontent.com/35700575/236502824-df94662b-6dbe-4928-b72a-8a231007a8da.png)

This way

**Comment by ldmpub** [comment]
Same error here when installing the add-on under Freeplane 1.11.1:

![image](https://user-images.githubusercontent.com/1452146/236573253-c36ea93c-4ce4-4f63-9326-846d05573fb1.png)

**Comment by barrymac** [comment]
thanks for the feedback people, this change is in the latest version
