### ISSUE TITLE
Unable to make the add-on work ... (future Setup Documentation?😂)

### ISSUE THREAD

**Issue by ldmpub** [barrymac/freeplane_openai_addon#4]
Hi,

After #1 fix, I managed to install the add-on 👍 but I failed to make it run in Freeplane despite the below configuration steps I guess all users will have to perform ... 

Please correct me if I'm wrong and give me (= to all of us) the correct and detailed instructions 🙏.

💡Tip: Don't hesitate to start a Documentation based on the below text 😋 (for instance by activation of the Wiki feature in the current GitHub repo).

---

# Pre-requisites
Check-list before starting
- [ ] I have an **Open AI account**
- [ ] **Freeplane app is installed** on my computer
- [ ] **Open AI add-on is installed** in Freeplane.

# Step by step configuration of Freeplane Open AI add-on

## In your Open AI Account

1. **Go to** web page https://platform.openai.com/account/api-keys
2. **Log in** using your ChatGPT account
3. **Create a new Key** by clicking on "Create a new secret Key" button like shown bellow and finally **copy this newly generated key**.

![API Key for GPT](https://user-images.githubusercontent.com/1452146/236701790-1737ef61-6493-4d88-a3b5-e391404221c0.jpg)

## In Freeplane

1. Start the Freeplane app and go to menu **Tools > Add-ons**
2. Then click on the **Add-ons tab**, select the **ChatGPT add-on** and click on **Configure**
3. Finally **paste the GPT key** from  your clipboard into the field "Open AI API key".

... you're done.

**Comment by barrymac** [comment]
great suggestion! Thank you!
