### ISSUE TITLE
Error: Text must not be null or empty

### ISSUE THREAD

**Issue by ldmpub** [barrymac/freeplane_openai_addon#5]
**Context**
* Freeplane 1.11.1
* Freeplane Open AI addon 0.2.1
* OS Windows 10 (running in french).

**Addon-configuration done**
* See : #4

**Result**
When selecting a node and running the addon by clicking on "GPT Ideas", the following error is returned in a Dialog box:
`Text must not be null or empty `
![image](https://user-images.githubusercontent.com/1452146/236702943-14d985c2-29cc-4598-b799-4f1a9cc65859.png)

Thanks in advance for your help,

**Comment by barrymac** [comment]
can you try again with the latest update please?

**Comment by ldmpub** [comment]
Thanks 👍.

✅New add-on version installed => 
![image](https://user-images.githubusercontent.com/1452146/237056624-e12aea62-04d1-40f1-b820-aa58296e2907.png)

✅Freeplane updated to Freeplane 1.11.2

✅Add-on configuration simplified:
![Freeplane - Add configuration](https://user-images.githubusercontent.com/1452146/237056958-22f27dd4-b487-42e5-873a-c3b09bd82a04.jpg)

❌Still the same error message when running:

https://user-images.githubusercontent.com/1452146/237057066-887edc95-6392-4e25-8446-84ee5089c164.mp4

Note: I have checked => ChatGPT is working on my computer = my Internet connexion is OK.


💡Waiting for your ideas to solve this issue ...

**Comment by EdoFro** [comment]
I had the same error because I had no more free OpenAI API access. I had to add a pay method and buy for new access.

**Comment by ldmpub** [comment]
@EdoFro thanks because you are right: contrary to ChatGPT, OpenAI API access is not free and it looks like I have exceeded my "usage quota + validity date" 😛 ; I have not planned to pay for this experimental service => the game is over for me ...

![image](https://github.com/barrymac/freeplane_openai_addon/assets/1452146/f2df0f01-82dc-4a6a-bfea-9ec0a7050c20)

Last message to all you folks: "Have fun" 🎉


PS for @barrymac: maybe you can add a "trouble shooting section" in the add-on Documentation to ask user to check his OpenAI API credit at https://platform.openai.com/account/usage?

**Comment by EdoFro** [comment]
I paid for it with a monthly limit of US$ 10 and a alarm message at US$ 4 (you can set both parameters as you like).

I used the addon a few times and it charged me something like US$ 0.00012

I roughly calculated I could used it 50000 times to get to the US$ 5 (maybe I'm wrong, but I was sure I wont use it so much) 

It is not a monthly defined amount, it just charges you the amount you use it.

**Comment by EdoFro** [comment]
@ldmpub,
here is what it costed me to use the add-on something like 10 times:

![image](https://github.com/barrymac/freeplane_openai_addon/assets/35700575/48135eb6-08b3-4062-9349-03eb590c694d)

Let's asume I used it just 5 times: that means that for US$ 5, I can use the add-on 10040 times.

I think that, if I can tune this add-on to my needs, I´m going to save a lot more than 5 bucks in productivity.

BR,
edo

**Comment by barrymac** [comment]
I burn through a lot more credit than that with https://github.com/Significant-Gravitas/Auto-GPT especially with GPT-4. I'll tr it when my credit runs out. Clearly I should trap this error gracefully and display something useful.

**Comment by EdoFro** [comment]
@barrymac,
you can add an `else`  or a `switch case` statement [here](https://github.com/barrymac/freeplane_openai_addon/blob/15d3971c6ac12bd2298f5dfd31400b0c446503d0/scripts/openAiGpt.groovy#LL99C1-L102C10)
 I can't do it now. Maybe later.

I remember I received [response 429](https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details)

more info: [API Error Codes Explained](https://help.openai.com/en/collections/3808446-api-error-codes-explained)

**Comment by barrymac** [comment]
Ah of course!  Thank you @EdoFro , the openAI status codes page is very convenient! 

![429](https://github.com/barrymac/freeplane_openai_addon/assets/14211/d69f49fc-3c32-49a1-a779-bf109a457dd5)
